## This is a AWS tool that was modifed to include a Jira backend
## Some of the items in this repo are original and some are added for the WP installation

stack_name: aws-health-aware
template: CFN_DEPLOY_AHA.yml

params:
  AWSHealthEventType: "issue | accountNotification | scheduledChange"
  AWSOrganizationsEnabled:	Yes
  EventSearchBack: 12
  JiraInstanceSecretParam: BLANK_TO_CREATE_MANUALLY
  ManagementAccountRoleArn: arn:aws:iam::537691856263:role/custodian-health-read
  Regions: us-east-1,us-east-2,ap-southeast-2,eu-central-1,ap-northeast-1
  S3Bucket: bootstrap-region-regionalresourcesbucket-9rzrq97wbtw4
  S3Key: deploy-artifacts/aha-2.0.0-custom.zip
  SecondaryRegion: No
